#ifndef EC_NM_API_LIB_ERR
#define EC_NM_API_LIB_ERR

/** \file: EC_Network_Api_Err.h
 * Date Modified: 04/20/2016
 *
 * Error code used by the Network Management API for EtherCAT
 *
 */

/**
 *
 * Enum for Network Management API Error
 *
 */
typedef enum{
	EC_API_ERROR_NONE,			
	EC_API_ERROR_MEMORY_ALLOC_FAILED      = 0x00000100,
	EC_API_ERROR_PE_IS_NOT_RUNNING,
	EC_API_ERROR_CONTROL_CHANNEL_LOCK_FAILED,
	EC_API_ERROR_CONTROL_CHANNEL_EVENT_FAILED,
	EC_API_ERROR_CONTROL_CHANNEL_WAITEVENT_FAILED,
	EC_API_ERROR_CONTROL_CHANNEL_SHAREDMEMORY_FAILED,
	EC_API_ERROR_CONTROL_CHANNEL_LOCK_WAIT_TIMEOUT,
	EC_API_ERROR_API_CHANNEL_ERROR,
	EC_API_ERROR_API_CHANNEL_TIMEOUT,
	EC_API_ERROR_STATUS_CHANNEL_ERROR,

	EC_API_ERROR_RTSS_FILE_NOT_FOUND,
	EC_API_ERROR_RTSS_START_ERROR,
	EC_API_ERROR_REQUEST_CHANNEL_TIMEOUT,
	EC_API_ERROR_FREE_CHANNEL_TIMEOUT,
	EC_API_ERROR_CLOSE_DEVICE_TIMEOUT,

	EC_API_ERROR_REQUESTCHANNEL_FAILED,
	EC_API_ERROR_REACH_MAX_CHANNEL_NUMBER,
	EC_API_ERROR_FREE_CHANNEL_FAILED,
	EC_API_ERROR_INVALID_CHANNEL_ID,
	EC_API_ERROR_CLOSE_DEVICE_FAILED,

	EC_API_ERROR_STATUS_CHANNEL_NULL,
	EC_API_ERROR_STATUS_CHANNEL_ID_ERROR,
	EC_API_ERROR_STATUS_SHAREDMEMORY_VERSION_ERROR,
	EC_API_ERROR_STATUS_SHAREDMEMORY_CHANNEL_INDEX_ERROR,

	EC_API_ERROR_CREATE_DEVICE_LOCK_ERROR,
	EC_API_ERROR_CLOSE_DEVICE_LOCK_ERROR,

	EC_API_ERROR_DEVICE_IS_NULL,
	EC_API_ERROR_NOT_SUPORTED_FUNCTION,

	EC_API_ERROR_COMMAND_QUEUE_ADD_FAILED,
	EC_API_ERROR_COMMAND_QUEUE_IS_FULL,
	EC_API_ERROR_COMMAND_QUEUE_ADD_TIMEOUT,		

	EC_API_ERROR_COMMAND_ID_LOCK_ERROR,
	EC_API_ERROR_COMMAND_ID_GET_ERROR,

	EC_API_ERROR_CALLBACK_MALLOC_FAILED,
	EC_API_ERROR_CALLBACK_THREAD_NULL,
	EC_API_ERROR_CALLBACK_THREAD_ERROR,
	EC_API_ERROR_CALLBACK_THREAD_TIMEOUT,

	EC_API_ERROR_ARGUMENT_OUT_OF_RANGE = 0x20000000,
	EC_API_ERROR_ARGUMENT_IS_NULL,
	EC_API_ERROR_SCAN_NETWORK_FAILED,
	EC_API_ERROR_SLAVE_STATE_CHANGE_ERROR,
	EC_API_ERROR_SLAVE_SDO_STATUS_BELOW_PREOP,
	EC_API_ERROR_SLAVE_INVALID_ADDRESSING_MODE,
	EC_API_ERROR_SLAVE_SDO_DOWNLOAD_ERROR,
	EC_API_ERROR_SLAVE_SDO_UPLOAD_ERROR,
	EC_API_ERROR_SLAVE_SDO_INOF_GET_OD_LIST_ERROR,
	EC_API_ERROR_SLAVE_SDO_INOF_GET_OD_ERROR,
	EC_API_ERROR_SLAVE_SDO_INOF_GET_ED_ERROR,
	EC_API_ERROR_SLAVE_ACTUAL_SIZE_LARGER_THAN_BUFFER_SIZE,
	EC_API_ERROR_CALLBACK_FUNC_ERROR,
	EC_API_ERROR_CALLBACK_FUNC_TIMEOUT,
	EC_API_ERROR_CALLBACK_FUNC_INVALID_STATE,
	EC_API_ERROR_SLAVE_REG_WRITE_ERROR,
	EC_API_ERROR_SLAVE_REG_READ_ERROR,
	EC_API_ERROR_SLAVE_SII_WRITE_ERROR,
	EC_API_ERROR_SLAVE_SII_READ_ERROR,
	EC_API_ERROR_SLAVE_PDO_READWRITE_NOT_ALLOWED,
	EC_API_ERROR_SLAVE_PDO_READWRITE_TIMEOUT,
	EC_API_ERROR_SLAVE_PDO_NOT_MAPPED,
	EC_API_ERROR_SLAVE_TX_PDO_WRITE_NOT_ALLOWED,
	EC_API_ERROR_SLAVE_FOE_NOT_IN_BOOT_STATE,			
	EC_API_ERROR_SLAVE_FOE_FILE_OPEN_ERROR,			
	EC_API_ERROR_SLAVE_FOE_READ_ERROR,			
	EC_API_ERROR_SLAVE_FOE_WRITE_ERROR,
	EC_API_ERROR_SLAVE_FOE_FILE_PATH_TOO_LONG,
	EC_API_ERROR_SLAVE_FOE_FILE_NAME_TOO_LONG,
	EC_API_ERROR_AXIS_IS_NOT_SERVO_ON,
	EC_API_ERROR_NOT_IN_PP_MODE,
	EC_API_ERROR_PDO_NOT_MAPPED,
	EC_API_ERROR_NOT_IN_HM_MODE,

	EC_API_ERROR_OPEN_COM_FAILED,
	EC_API_ERROR_CREAD_COM_PROCESS_THREAD_FAILED,

	EC_API_ERROR_OTHER_ERROR,	 
	EC_API_ERROR_UNKNOWN_ERROR
}EC_API_ERROR_CODE;

#endif