/** \file EC_Network_Api.h
 * Date Modified: 04/20/2016
 *
 * EtherCAT Master Network API Library
 *
 * API library for to access and use EtherCAT Master status and function.
 */

#ifndef EC_NM_API_LIB
#define EC_NM_API_LIB

#ifdef __cplusplus
extern "C" {
#endif

#include "EC_Network_Api_Def.h"

/**
 * \defgroup basicApi Network API control
 * APIs to control and check status of Network Management library
 * @{
 */

/**
 * Create a connection to the active PlatformEngine_EtherCAT instance.
 * @param pDev	a pointer to a device descriptor. Value must be null before passing a pointer to the ecCreateDevice.
 * @return		Result of the API call or EC_API_ERROR_CODE_DEVICE_POINTER_IS_NOT_NULL
 * @see			ecCloseDevice
 * @see			EC_API_ERROR_CODE
 */
EC_API ecCreateDevice(PECDEV pDev);

/**
 * Close a connection to the PlatformEngine_EtherCAT.
 * @param dev	device descriptor
 * @return		Result of the API call or EC_API_ERROR_CODE_DEVICE_IS_NULL
 * @see			ecCreateDevice
 * @see			EC_API_ERROR_CODE
 */
EC_API ecCloseDevice(ECDEV dev);

/**
 * Get the last error that was generated by a failed API call.
 * @param dev	device descriptor
 * @return		Error code (EC_API_ERROR_CODE_DEVICE_IS_NULL can be previous error, or error resulting from device handler passed to this function was NULL)
 * @see			EC_API_ERROR_CODE
*/
EC_API ecGetLastError(ECDEV dev);

/**
 * Close a connection of specified Network Management API channel to the PlatformEngine_EtherCAT.
 * @param deviceId	deviceID of the api channel to close. Please note this is a deviceID of Network Management API channel.
 * @return		Result of the API call
 * @see			ecCreateDevice
 * @see			EC_API_ERROR_CODE
 */
EC_API ecForceCloseDevice(int deviceId);

/**
 * Get a list including all active devices id.
 * @param *list pointer to EC_ACT_DEV_LIST that will contain the active device count and id of active device.
 * @return		Result of the API call or EC_API_ERROR_NULL_ARG
 * @see			ecForceCloseDevice
 * @see			EC_API_ERROR_CODE
 */
EC_API ecGetActiveDeviceList(EC_ACT_DEV_LIST* list);

/**@}*/

/**
 * \defgroup masterStatus Master Status
 * APIs to get current master information and status
 * @{
 */

/**
 * Get current state of the EtherCAT master.
 * @param dev	device descriptor
 * @param pCurState	Pointer to EC_MASTER_STATE to store current master state
 * @return		Result of the API call or EC_API_ERROR_CODE_DEVICE_IS_NULL
 * @see			ecCreateDevice
 * @see			ecCloseDevice
 * @see			EC_API_ERROR_CODE
 */
EC_API ecGetMasterState(ECDEV dev, PEC_MASTER_STATE pCurState);

/**
 * Get current status of the EtherCAT master including master status, DC status, topology (Ring) status, HotConnect status and HotConnect abort status.
 * @param dev	device descriptor
 * @param pStatus	Pointer to EC_MASTER_STATUS to store current master status.
 * @return		Result of the API call or EC_API_ERROR_CODE_DEVICE_IS_NULL
 * @see			ecCreateDevice
 * @see			ecCloseDevice
 * @see			EC_API_ERROR_CODE
 */
EC_API ecGetMasterStatus(ECDEV dev, PEC_MASTER_STATUS pStatus);

/**
 * Get performance statistics of the EtherCAT master.
 * @param dev	device descriptor
 * @param performData	Pointer to EC_MASTER_PERFORM_DATA to store current master performance data.
 * @return		Result of the API call or EC_API_ERROR_CODE_DEVICE_IS_NULL
 * @see			ecCreateDevice
 * @see			ecCloseDevice
 * @see			EC_API_ERROR_CODE
 */
EC_API ecGetMasterStatistics(ECDEV dev, PEC_MASTER_PERFORM_DATA performData);

/**
 * Clear performance statistics data of the EtherCAT master.
 * @param dev	device descriptor
 * @return		Result of the API call or EC_API_ERROR_CODE_DEVICE_IS_NULL
 * @see			ecCreateDevice
 * @see			ecCloseDevice
 * @see			EC_API_ERROR_CODE
 */
EC_API ecClearMasterStatistics(ECDEV dev);

/**
 * Start searching for newly connected cables and slaves if HotConnect option is available.
 * @param dev	device descriptor
 * @return		Result of the API call or EC_API_ERROR_CODE_DEVICE_IS_NULL
 * @see			ecCreateDevice
 * @see			ecCloseDevice
 * @see			EC_API_ERROR_CODE
 */
EC_API ecStartHotConnect(ECDEV dev);

/**
 * Start searching for newly connected cables and slaves if HotConnect option is available.
 * This API is blocking API returning if HotConnect procedure has been finished or halted by any error.
 * @param dev	device descriptor
 * @return		Result of the API call or EC_API_ERROR_CODE_DEVICE_IS_NULL
 * @see			ecCreateDevice
 * @see			ecCloseDevice
 * @see			EC_API_ERROR_CODE
 */
EC_API ecStartHotConnectWithRes(ECDEV dev);

/**
 * Clear latched HotConnect abortion flag.
 * @param dev	device descriptor
 * @return		Result of the API call or EC_API_ERROR_CODE_DEVICE_IS_NULL
 * @see			ecCreateDevice
 * @see			ecCloseDevice
 * @see			EC_API_ERROR_CODE
 */
EC_API ecClearHotConnectAbortionFlag(ECDEV dev);

//EC_API ecGetMasterLog(ECDEV dev, pLog);
//EC_API ecClearMasterLog(ECDEV dev);

/**@}*/

/**
 * \defgroup networkStatus Network Status
 * APIs to get Network Status
 * @{
 */

/**
 * Get node count the system is currently managing. This number will be the total of onlineNodeCount + offlineNodeCount + unknownNodeCount.
 * @param dev	device descriptor
 * @param pCount	Pointer to an integer variable to store the slave count
 * @return		Result of the API call or EC_API_ERROR_CODE_DEVICE_IS_NULL
 * @see			ecCreateDevice
 * @see			ecCloseDevice
 * @see			ecGetOnlineSlaveCount
 * @see			ecGetOfflineSlaveCount
 * @see			ecGetUnknownSlaveCount
 * @see			EC_API_ERROR_CODE
 */
EC_API ecGetTotalSlaveCount(ECDEV dev, int  *pCount);

//EC_API ecGetDefSlaveList(ECDEV dev, PEC_MASTER_SLAVE_LIST pSlaves);

/**
 * Get a filename of the current active Master Configuration file used by PlatformEngine_EtherCAT instance. \warning Reserved for future use.
 * @param dev	a pointer to a device descriptor\
 * @param filename	pointer to char array to store the filename
 * @param bufferSize	size of the char array buffer
 * @return		Result of the API call or EC_API_ERROR_CODE_DEVICE_IS_NULL
 * @see			ecCreateDevice
 * @see			ecCloseDevice
 * @see			ecSetDefFilename
 * @see			EC_API_ERROR_CODE
 */
EC_API ecGetMasterConfigFilename(ECDEV dev, TCHAR *filename, int bufferSize);

/**
 * Set an new filename used by PlatformEngine_EtherCAT as a Master Configuration file next time. \warning Reserved for future use.
 * @param dev	a pointer to a device descriptor
 * @param filename	pointer to char array where the new filename is stored
 * @return		Result of the API call or EC_API_ERROR_CODE_DEVICE_IS_NULL
 * @see			ecCreateDevice
 * @see			ecCloseDevice
 * @see			ecSetDefFilename
 * @see			EC_API_ERROR_CODE
 */
EC_API ecSetMasterConfigFilename(ECDEV dev, TCHAR *filename);

/**
 * Get online node count on the network. Slaves registered to the master and existing on the network will become online. 
 * This number will be updated when slaves are connected or disconnected if HotConnect function is in use
 * @param dev	device descriptor
 * @param pCount	Pointer to an integer variable to store the slave count
 * @return		Result of the API call or EC_API_ERROR_CODE_DEVICE_IS_NULL
 * @see			ecCreateDevice
 * @see			ecCloseDevice
 * @see			ecGetTotalSlaveCount
 * @see			ecGetOfflineSlaveCount
 * @see			ecGetUnknownSlaveCount
 * @see			EC_API_ERROR_CODE
 */
EC_API ecGetOnlineSlaveCount(ECDEV dev, int  *pCount);

/**
 * Get offline node count on the network. Slaved registered to the master, but does not existing on the network will be recognized by
 * the master as offline slave. This number will be updated when slaves are connected or disconnected when HotConnect function is in use
 * @param dev	device descriptor
 * @param pCount	Pointer to an integer variable to store the slave count
 * @return		Result of the API call or EC_API_ERROR_CODE_DEVICE_IS_NULL
 * @see			ecCreateDevice
 * @see			ecCloseDevice
 * @see			ecGetTotalSlaveCount
 * @see			ecGetOnlineSlaveCount
 * @see			ecGetUnknownSlaveCount
 * @see			EC_API_ERROR_CODE
 */
EC_API ecGetOfflineSlaveCount(ECDEV dev, int  *pCount);

/**
 * Get unknown node count on the network. Unknown slave is a slave existing on the network but is not registered to the master and is 
 * not available for to use.This number will be updated when slaves are connected or disconnected when HotConnect function is in use
 * @param dev	device descriptor
 * @param pCount	Pointer to an integer variable to store the slave count
 * @return		Result of the API call or EC_API_ERROR_CODE_DEVICE_IS_NULL
 * @see			ecCreateDevice
 * @see			ecCloseDevice
 * @see			ecGetTotalSlaveCount
 * @see			ecGetOnlineSlaveCount
 * @see			ecGetOfflineSlaveCount
 * @see			EC_API_ERROR_CODE
 */
EC_API ecGetUnknownSlaveCount(ECDEV dev, int  *pCount);

//EC_API ecGetSlaveList(ECDEV dev, PEC_MASTER_SLAVE_LIST pSlaves);

/**@}*/

/**
 * \defgroup slaveControl Slave Control
 * APIs to control or read from/write to slave
 * @{
 */

/** 
 * Get information of the slave specified. Information includes VendorId, ProductCode, ConfiguredId, mapped dio size, mapped axis number, etc.
 * @param dev	device descriptor
 * @param nodeId	NodeId starting from 0 up to totalNodeCount-1.
 * @param pSlaveInfo	Pointer to slave info struct to save the result.
 * @return		Result of the API call or EC_API_ERROR_CODE_DEVICE_IS_NULL
 * @see			ecCreateDevice
 * @see			ecCloseDevice
 * @see			ecGetSlaveState
 * @see			EC_API_ERROR_CODE
 */
EC_API ecGetSlaveInfo(ECDEV dev, int nodeId, PEC_SLAVE_INFO pSlaveInfo);

/** 
 * Get the AL State of the slave specified.
 * @param dev	device descriptor
 * @param configuredId	ConfiguredID assigned to the slave by a master to the slave to communicate, retrieved from ecGetSlaveInfo
 * @param pCurState	Pointer to a variable to store the current AL status of the slave specified
 * @return		Result of the API call or EC_API_ERROR_CODE_DEVICE_IS_NULL
 * @see			ecCreateDevice
 * @see			ecCloseDevice
 * @see			ecGetSlaveInfo
 * @see			ecSetSlaveState
 * @see			EC_API_ERROR_CODE
 */
EC_API ecGetSlaveState(ECDEV dev, int configuredId, PEC_SLAVE_STATE pCurState);
//EC_API ecGetSlaveIcon(ECDEV dev, unsigned char *iconData);


/** 
 * Set the AL Status of the slave specified.
 * @param dev	device descriptor
 * @param configuredId	ConfiguredID of the slave to communicate
 * @param newState	A variable storing new AL state of the slave specified
 * @return		Result of the API call or EC_API_ERROR_CODE_DEVICE_IS_NULL
 * @see			ecCreateDevice
 * @see			ecCloseDevice
 * @see			ecGetSlaveInfo
 * @see			ecGetSlaveState
 * @see			EC_API_ERROR_CODE
 */
EC_API ecSetSlaveState(ECDEV dev, int configuredId, EC_SLAVE_STATE newState);

/** 
 * Send data to slave via SDO communication
 * @param dev	device descriptor
 * @param configuredId	ConfiguredID of the slave to communicate
 * @param index	CANopen object Index
 * @param subIndex CANopen object Subindex
 * @param length	CANopen object size
 * @param sdoType	SDO communication type.
 * @param *data	data to set to the CANopen object
 * @return		Result of the API call or EC_API_ERROR_CODE_DEVICE_IS_NULL
 * @see			ecCreateDevice
 * @see			ecCloseDevice
 * @see			ecUploadSDO
 * @see			EC_API_ERROR_CODE
 */
EC_API ecDownloadSDO(ECDEV dev, int configuredId, unsigned short index, unsigned char subIndex, int length, EC_MASTER_SDO_TYPE sdoType, unsigned char *data);

/** 
 * Receive data from slave via SDO communication
 * @param dev	device descriptor
 * @param configuredId	ConfiguredID of the slave to communicate
 * @param index	CANopen object Index
 * @param subIndex CANopen object Subindex
 * @param length	CANopen object size
 * @param sdoType	SDO communication type.
 * @param *data	data to set to the CANopen object
 * @return		Result of the API call or EC_API_ERROR_CODE_DEVICE_IS_NULL
 * @see			ecCreateDevice
 * @see			ecCloseDevice
 * @see			ecDownloadSDO
 * @see			EC_API_ERROR_CODE
 */
EC_API ecUploadSDO(ECDEV dev, int configuredId, unsigned short index, unsigned char subIndex, int length, EC_MASTER_SDO_TYPE sdoType, unsigned char *data);

/** 
 * Send data to slave via SDO communication
 * @param dev	device descriptor
 * @param configuredId	ConfiguredID of the slave to communicate
 * @param index	CANopen object Index
 * @param subIndex CANopen object Subindex
 * @param length	CANopen object size
 * @param sdoType	SDO communication type.
 * @param *data	data to set to the CANopen object
 * @param retryCount Number of count to retry
 * @param retryInterval interval between retry in ms.
 * @return		 EC_API_ERROR_CODE_DEVICE_IS_NULL, 0: Succeed, -1: retryCount must be bigger than 0, -2: retryInterval must be more than 0
 * @see			EC_API_ERROR_CODE
 */
int ecDownloadSDOEx(ECDEV dev, int configuredId, unsigned short index, unsigned char subIndex, int length, EC_MASTER_SDO_TYPE sdoType, unsigned char *data, int retryCount, int retryInterval);

/** 
 * Receive data from slave via SDO communication
 * @param dev	device descriptor
 * @param configuredId	ConfiguredID of the slave to communicate
 * @param index	CANopen object Index
 * @param subIndex CANopen object Subindex
 * @param length	CANopen object size
 * @param sdoType	SDO communication type.
 * @param *data	data to set to the CANopen object
 * @param retryCount Number of count to retry
 * @param retryInterval interval between retry in ms.
 * @return		 EC_API_ERROR_CODE_DEVICE_IS_NULL, 0: Succeed, -1: retryCount must be bigger than 0, -2: retryInterval must be more than 0
 * @see			EC_API_ERROR_CODE
 */
int ecUploadSDOEx(ECDEV dev, int configuredId, unsigned short index, unsigned char subIndex, int length, EC_MASTER_SDO_TYPE sdoType, unsigned char *data, int retryCount, int retryInterval);

/** 
 * Write to the register area of ESC on the slave specified.
 * Size must be between 1 byte to 8 bytes
 * @param dev	device descriptor
 * @param location	location of the slave to communicate
 * @param address	register address to write
 * @param size		size to write. Must be between 1 to 8.
 * @param *data	Data to write to the register specified
 * @return		Result of the API call or EC_API_ERROR_CODE_DEVICE_IS_NULL
 * @see			ecCreateDevice
 * @see			ecCloseDevice
 * @see			ecRawRead
 * @see			ecGetSlaveInfo
 * @see			EC_API_ERROR_CODE
 */
EC_API ecRawWrite(ECDEV dev, int location, unsigned short address, unsigned int size, unsigned char *data);

/** 
 * Read from register area of ESC on the slave specified.
 * Size must be between  1 byte to 8 bytes
 * @param dev	device descriptor
 * @param location	location of the slave to communicate
 * @param address	register address to write
 * @param size		size to read. Must be between 1 and 8.
 * @param *data	Buffer to store the date read from the register
 * @return		Result of the API call or EC_API_ERROR_CODE_DEVICE_IS_NULL
 * @see			ecCreateDevice
 * @see			ecCloseDevice
 * @see			ecRawWrite
 * @see			ecGetSlaveInfo
 * @see			EC_API_ERROR_CODE
 */
EC_API ecRawRead(ECDEV dev, int location, unsigned short address, unsigned int size, unsigned char *data);

/** 
 * Read from SII area in an EEPROM on the slave specified with location ID. Read 2 bytes at once due to the limitation of the SII specification.
 * @param dev	device descriptor
 * @param configuredId	ConfiguredID of the slave to communicate
 * @param address	SII address to write
 * @param *data	Buffer to store the date read from the SII
 * @return		Result of the API call or EC_API_ERROR_CODE_DEVICE_IS_NULL
 * @see			ecCreateDevice
 * @see			ecCloseDevice
 * @see			ecGetSlaveCount
 * @see			EC_API_ERROR_CODE
 */
EC_API ecReadSII(ECDEV dev, int configuredId, unsigned short address, unsigned char *data);

/** 
 * Write to SII area in an EEPROM on the slave specified with ConfiguredID. Write 2 bytes at once due to the limitation of the SII specification.
 * Check sum at 0x07 will be updated automatically at the same time when witting to 0x00 to 0x06.
 * @param dev	device descriptor
 * @param configuredId	ConfiguredID of the slave to communicate
 * @param address	SII address to write
 * @param *data	Data to write to the SII
 * @return		Result of the API call or EC_API_ERROR_CODE_DEVICE_IS_NULL
 * @see			ecCreateDevice
 * @see			ecCloseDevice
 * @see			ecGetSlaveCount
 * @see			EC_API_ERROR_CODE
 */
EC_API ecWriteSII(ECDEV dev, int configuredId, unsigned short address, unsigned char *data);

/** 
 * Read from SII area in an EEPROM on the slave specified with location ID. Read 2 bytes at once due to the limitation of the SII specification.
 * @param dev	device descriptor
 * @param locationId	Location of the slave to communicate with
 * @param address	SII address to write
 * @param *data	Buffer to store the date read from the SII
 * @return		Result of the API call or EC_API_ERROR_CODE_DEVICE_IS_NULL
 * @see			ecCreateDevice
 * @see			ecCloseDevice
 * @see			ecGetSlaveCount
 * @see			EC_API_ERROR_CODE
 */
EC_API ecIncReadSII(ECDEV dev, int locationId, unsigned short address, unsigned char *data);

/** 
 * Write to SII area in an EEPROM on the slave specified with location ID. Write 2 bytes at once due to the limitation of the SII specification.
 * Check sum at 0x07 will be updated automatically at the same time when witting to 0x00 to 0x06.
 * @param dev	device descriptor
 * @param locationId	Location of the slave to communicate with
 * @param address	SII address to write
 * @param *data	Data to write to the SII
 * @return		Result of the API call or EC_API_ERROR_CODE_DEVICE_IS_NULL
 * @see			ecCreateDevice
 * @see			ecCloseDevice
 * @see			ecGetSlaveCount
 * @see			EC_API_ERROR_CODE
 */
EC_API ecIncWriteSII(ECDEV dev, int locationId, unsigned short address, unsigned char *data);

/**
 * Get the device ID of the specified device.
 * @param dev	device descriptor
 * @param *pId	pointer to int that will contain the device id
 * @return		Result of the API call or EC_API_ERROR_CODE_DEVICE_IS_NULL
 */
EC_API ecGetDeviceID(ECDEV dev, int *pId);

/**
 * Get the device count.
 * @param dev	device descriptor
 * @param *pCount pointer to int that will contain the device count
 * @return		Result of the API call or EC_API_ERROR_CODE_DEVICE_IS_NULL
 * @see			EC_API_ERROR_CODE
 */
EC_API ecGetDeviceCount(ECDEV dev, int *pCount);

/**
 * Read file from a slave using FoE.
 * \warning NOT FUNCTIONING IN THIS VERSION
 * @param dev	device descriptor
 * @param configuredId ConfiguredID of the slave to read from.
 * @param filename pointer to filename char array
 * @param path pointer to path char array
 * @param password integer password
 * @return		Result of the API call or EC_API_ERROR_CODE_DEVICE_IS_NULL
 * @see			EC_API_ERROR_CODE
 */
EC_API ecUploadFile(ECDEV dev, int configuredId, TCHAR *filename, TCHAR *path, int password);

/**
 * Write file to a slave. The slave must be in bootstrap state prior to calling this API.
 * @param dev	device descriptor
 * @param configuredId ConfiguredID of the slave to read from.
 * @param filename pointer to filename char array
 * @param path pointer to path char array
 * @param password integer password
 * @return		Result of the API call or EC_API_ERROR_CODE_DEVICE_IS_NULL
 * @see			ecSetSlaveState
 * @see			ecGetLastError
 * @see			EC_API_ERROR_CODE
 */
EC_API ecDownloadFile(ECDEV dev, int configuredId, TCHAR *filename, TCHAR *path, int password);


#ifdef __cplusplus
}
#endif

/**@}*/
#endif
