// EC_Network_Api_Sim.h
// Header-only wrapper for VS2012 compatibility
// Provides EC_Network_Api interface that internally calls WMXBroker DLL
//
// Usage:
//   Replace #include "EC_Network_Api.h" with #include "EC_Network_Api_Sim.h"
//   Link with WMXBroker.lib

#ifndef EC_NETWORK_API_SIM_H
#define EC_NETWORK_API_SIM_H

#include <windows.h>
#include <tchar.h>

// WMX 1.5 type definitions
#include "EC_Network_Api_Def.h"

#ifdef __cplusplus
extern "C" {
#endif

// DLL Import declarations
#ifdef WMXBROKER_EXPORTS
#define ECBROKER_CAPI __declspec(dllexport)
#else
#define ECBROKER_CAPI __declspec(dllimport)
#endif

//=============================================================================
// Device Management APIs
//=============================================================================

/**
 * Create a connection to the active PlatformEngine_EtherCAT instance.
 * @param pDev a pointer to a device descriptor
 * @return Result of the API call
 */
ECBROKER_CAPI long __stdcall ecCreateDevice(PECDEV pDev);

/**
 * Close a connection to the PlatformEngine_EtherCAT.
 * @param dev device descriptor
 * @return Result of the API call
 */
ECBROKER_CAPI long __stdcall ecCloseDevice(ECDEV dev);

/**
 * Get the last error that was generated by a failed API call.
 * @param dev device descriptor
 * @return Error code
 */
ECBROKER_CAPI long __stdcall ecGetLastError(ECDEV dev);

/**
 * Close a connection of specified Network Management API channel.
 * @param deviceId deviceID of the api channel to close
 * @return Result of the API call
 */
ECBROKER_CAPI long __stdcall ecForceCloseDevice(int deviceId);

/**
 * Get a list including all active devices id.
 * @param list pointer to EC_ACT_DEV_LIST
 * @return Result of the API call
 */
ECBROKER_CAPI long __stdcall ecGetActiveDeviceList(EC_ACT_DEV_LIST* list);

/**
 * Get the device ID of the specified device.
 * @param dev device descriptor
 * @param pId pointer to int that will contain the device id
 * @return Result of the API call
 */
ECBROKER_CAPI long __stdcall ecGetDeviceID(ECDEV dev, int* pId);

/**
 * Get the device count.
 * @param dev device descriptor
 * @param pCount pointer to int that will contain the device count
 * @return Result of the API call
 */
ECBROKER_CAPI long __stdcall ecGetDeviceCount(ECDEV dev, int* pCount);

//=============================================================================
// Master Status APIs
//=============================================================================

/**
 * Get current state of the EtherCAT master.
 * @param dev device descriptor
 * @param pCurState Pointer to EC_MASTER_STATE
 * @return Result of the API call
 */
ECBROKER_CAPI long __stdcall ecGetMasterState(ECDEV dev, PEC_MASTER_STATE pCurState);

/**
 * Get current status of the EtherCAT master.
 * @param dev device descriptor
 * @param pStatus Pointer to EC_MASTER_STATUS
 * @return Result of the API call
 */
ECBROKER_CAPI long __stdcall ecGetMasterStatus(ECDEV dev, PEC_MASTER_STATUS pStatus);

/**
 * Get performance statistics of the EtherCAT master.
 * @param dev device descriptor
 * @param performData Pointer to EC_MASTER_PERFORM_DATA
 * @return Result of the API call
 */
ECBROKER_CAPI long __stdcall ecGetMasterStatistics(ECDEV dev, PEC_MASTER_PERFORM_DATA performData);

/**
 * Clear performance statistics data of the EtherCAT master.
 * @param dev device descriptor
 * @return Result of the API call
 */
ECBROKER_CAPI long __stdcall ecClearMasterStatistics(ECDEV dev);

//=============================================================================
// Network Status APIs
//=============================================================================

/**
 * Get total slave count.
 * @param dev device descriptor
 * @param pCount Pointer to slave count
 * @return Result of the API call
 */
ECBROKER_CAPI long __stdcall ecGetTotalSlaveCount(ECDEV dev, int* pCount);

/**
 * Get online slave count.
 * @param dev device descriptor
 * @param pCount Pointer to slave count
 * @return Result of the API call
 */
ECBROKER_CAPI long __stdcall ecGetOnlineSlaveCount(ECDEV dev, int* pCount);

/**
 * Get offline slave count.
 * @param dev device descriptor
 * @param pCount Pointer to slave count
 * @return Result of the API call
 */
ECBROKER_CAPI long __stdcall ecGetOfflineSlaveCount(ECDEV dev, int* pCount);

/**
 * Get unknown slave count.
 * @param dev device descriptor
 * @param pCount Pointer to slave count
 * @return Result of the API call
 */
ECBROKER_CAPI long __stdcall ecGetUnknownSlaveCount(ECDEV dev, int* pCount);

//=============================================================================
// Slave Control APIs
//=============================================================================

/**
 * Get information of the slave specified.
 * @param dev device descriptor
 * @param nodeId NodeId starting from 0
 * @param pSlaveInfo Pointer to slave info struct
 * @return Result of the API call
 */
ECBROKER_CAPI long __stdcall ecGetSlaveInfo(ECDEV dev, int nodeId, PEC_SLAVE_INFO pSlaveInfo);

/**
 * Get the AL State of the slave specified.
 * @param dev device descriptor
 * @param configuredId ConfiguredID of the slave
 * @param pCurState Pointer to current AL status
 * @return Result of the API call
 */
ECBROKER_CAPI long __stdcall ecGetSlaveState(ECDEV dev, int configuredId, PEC_SLAVE_STATE pCurState);

/**
 * Set the AL Status of the slave specified.
 * @param dev device descriptor
 * @param configuredId ConfiguredID of the slave
 * @param newState New AL state
 * @return Result of the API call
 */
ECBROKER_CAPI long __stdcall ecSetSlaveState(ECDEV dev, int configuredId, EC_SLAVE_STATE newState);

//=============================================================================
// SDO Communication APIs
//=============================================================================

/**
 * Send data to slave via SDO communication.
 * @param dev device descriptor
 * @param configuredId ConfiguredID of the slave
 * @param index CANopen object Index
 * @param subIndex CANopen object Subindex
 * @param length CANopen object size
 * @param sdoType SDO communication type
 * @param data data to set
 * @return Result of the API call
 */
ECBROKER_CAPI long __stdcall ecDownloadSDO(ECDEV dev, int configuredId,
    unsigned short index, unsigned char subIndex, int length,
    EC_MASTER_SDO_TYPE sdoType, unsigned char* data);

/**
 * Receive data from slave via SDO communication.
 * @param dev device descriptor
 * @param configuredId ConfiguredID of the slave
 * @param index CANopen object Index
 * @param subIndex CANopen object Subindex
 * @param length CANopen object size
 * @param sdoType SDO communication type
 * @param data buffer to receive data
 * @return Result of the API call
 */
ECBROKER_CAPI long __stdcall ecUploadSDO(ECDEV dev, int configuredId,
    unsigned short index, unsigned char subIndex, int length,
    EC_MASTER_SDO_TYPE sdoType, unsigned char* data);

//=============================================================================
// HotConnect APIs
//=============================================================================

/**
 * Start searching for newly connected cables and slaves.
 * @param dev device descriptor
 * @return Result of the API call
 */
ECBROKER_CAPI long __stdcall ecStartHotConnect(ECDEV dev);

/**
 * Start HotConnect and wait for completion.
 * @param dev device descriptor
 * @return Result of the API call
 */
ECBROKER_CAPI long __stdcall ecStartHotConnectWithRes(ECDEV dev);

/**
 * Clear latched HotConnect abortion flag.
 * @param dev device descriptor
 * @return Result of the API call
 */
ECBROKER_CAPI long __stdcall ecClearHotConnectAbortionFlag(ECDEV dev);

//=============================================================================
// Config APIs
//=============================================================================

/**
 * Get master configuration filename.
 * @param dev device descriptor
 * @param filename pointer to char array
 * @param bufferSize size of the char array buffer
 * @return Result of the API call
 */
ECBROKER_CAPI long __stdcall ecGetMasterConfigFilename(ECDEV dev, TCHAR* filename, int bufferSize);

/**
 * Set master configuration filename.
 * @param dev device descriptor
 * @param filename pointer to filename char array
 * @return Result of the API call
 */
ECBROKER_CAPI long __stdcall ecSetMasterConfigFilename(ECDEV dev, TCHAR* filename);

//=============================================================================
// Raw Register Read/Write APIs
//=============================================================================

/**
 * Write data to slave register.
 * @param dev device descriptor
 * @param location location of the slave (negative value for position)
 * @param address register address
 * @param size size of data to write
 * @param data pointer to data buffer
 * @return Result of the API call
 */
ECBROKER_CAPI long __stdcall ecRawWrite(ECDEV dev, int location, unsigned short address, unsigned int size, unsigned char* data);

/**
 * Read data from slave register.
 * @param dev device descriptor
 * @param location location of the slave (negative value for position)
 * @param address register address
 * @param size size of data to read
 * @param data pointer to data buffer
 * @return Result of the API call
 */
ECBROKER_CAPI long __stdcall ecRawRead(ECDEV dev, int location, unsigned short address, unsigned int size, unsigned char* data);

#ifdef __cplusplus
}
#endif

#endif // EC_NETWORK_API_SIM_H
